"""Initial migration

Revision ID: 552f56748ac5
Revises: 
Create Date: 2026-08-12 21:34:36.008170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '552f56748ac5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), server_default='user', nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('email_verification_token', sa.String(), nullable=True),
    sa.Column('email_verification_expires', sa.DateTime(), nullable=True),
    sa.Column('reset_token_hash', sa.String(), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('activity_level', sa.String(), nullable=True),
    sa.Column('unit_preference', sa.String(), nullable=False),
    sa.Column('goal_weight_kg', sa.Float(), nullable=True),
    sa.Column('sidebar_collapsed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('body_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('chest', sa.Float(), nullable=True),
    sa.Column('waist', sa.Float(), nullable=True),
    sa.Column('neck', sa.Float(), nullable=True),
    sa.Column('hip', sa.Float(), nullable=True),
    sa.Column('arm', sa.Float(), nullable=True),
    sa.Column('forearm', sa.Float(), nullable=True),
    sa.Column('thigh', sa.Float(), nullable=True),
    sa.Column('calf', sa.Float(), nullable=True),
    sa.Column('shoulders', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(), server_default='cm', nullable=False),
    sa.CheckConstraint('arm > 0', name='chk_measurement_arm_positive'),
    sa.CheckConstraint('calf > 0', name='chk_measurement_calf_positive'),
    sa.CheckConstraint('chest > 0', name='chk_measurement_chest_positive'),
    sa.CheckConstraint('forearm > 0', name='chk_measurement_forearm_positive'),
    sa.CheckConstraint('hip > 0', name='chk_measurement_hip_positive'),
    sa.CheckConstraint('neck > 0', name='chk_measurement_neck_positive'),
    sa.CheckConstraint('shoulders > 0', name='chk_measurement_shoulders_positive'),
    sa.CheckConstraint('thigh > 0', name='chk_measurement_thigh_positive'),
    sa.CheckConstraint('waist > 0', name='chk_measurement_waist_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_measurements_per_user_per_day')
    )
    with op.batch_alter_table('body_measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_body_measurements_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_measurements_user_id'), ['user_id'], unique=False)

    op.create_table('body_weight_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('body_fat_pct >= 0 AND body_fat_pct <= 100', name='chk_bodyfat_range'),
    sa.CheckConstraint('weight_kg > 0', name='chk_bodyweight_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_weight_per_user_per_day')
    )
    with op.batch_alter_table('body_weight_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_body_weight_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_weight_logs_user_id'), ['user_id'], unique=False)

    op.create_table('calorie_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fats_g', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('calories >= 0', name='chk_calories_nonnegative'),
    sa.CheckConstraint('carbs_g >= 0', name='chk_carbs_nonnegative'),
    sa.CheckConstraint('fats_g >= 0', name='chk_fats_nonnegative'),
    sa.CheckConstraint('protein_g >= 0', name='chk_protein_nonnegative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_calories_per_user_per_day')
    )
    with op.batch_alter_table('calorie_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calorie_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calorie_logs_user_id'), ['user_id'], unique=False)

    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('muscle_group', sa.String(), nullable=True),
    sa.Column('secondary_muscle', sa.String(), nullable=True),
    sa.Column('equipment', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'created_by', name='uq_exercise_name_per_owner')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercises_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_name'), ['name'], unique=False)

    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscriptions_id'), ['id'], unique=False)

    op.create_table('workout_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('share_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_templates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_templates_share_id'), ['share_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_workout_templates_user_id'), ['user_id'], unique=False)

    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_type', sa.String(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('target_reps', sa.Integer(), nullable=True),
    sa.Column('target_body_weight_kg', sa.Float(), nullable=True),
    sa.Column('target_calories', sa.Float(), nullable=True),
    sa.Column('target_protein_g', sa.Float(), nullable=True),
    sa.Column('target_workouts_per_week', sa.Integer(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('target_body_weight_kg > 0', name='chk_goal_bw_positive'),
    sa.CheckConstraint('target_calories >= 0', name='chk_goal_calories_nonnegative'),
    sa.CheckConstraint('target_protein_g >= 0', name='chk_goal_protein_nonnegative'),
    sa.CheckConstraint('target_reps > 0', name='chk_goal_reps_positive'),
    sa.CheckConstraint('target_weight_kg > 0', name='chk_goal_weight_positive'),
    sa.CheckConstraint('target_workouts_per_week > 0', name='chk_goal_workouts_positive'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_user_id'), ['user_id'], unique=False)

    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('exercises_count', sa.Integer(), nullable=False),
    sa.Column('sets_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('workout_template_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=False),
    sa.Column('target_reps', sa.Integer(), nullable=False),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('rest_seconds >= 0', name='chk_template_rest_nonnegative'),
    sa.CheckConstraint('target_reps > 0', name='chk_template_reps_positive'),
    sa.CheckConstraint('target_sets > 0', name='chk_template_sets_positive'),
    sa.CheckConstraint('target_weight_kg >= 0', name='chk_template_weight_nonnegative'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_template_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_template_exercises_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_template_exercises_template_id'), ['template_id'], unique=False)

    op.create_table('lift_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('set_number', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('reps > 0', name='chk_lift_reps_positive'),
    sa.CheckConstraint('rpe >= 0 AND rpe <= 10', name='chk_lift_rpe_range'),
    sa.CheckConstraint('weight_kg >= 0', name='chk_lift_weight_nonnegative'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lift_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lift_logs_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lift_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lift_logs_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lift_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lift_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lift_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_lift_logs_session_id'))
        batch_op.drop_index(batch_op.f('ix_lift_logs_id'))
        batch_op.drop_index(batch_op.f('ix_lift_logs_exercise_id'))

    op.drop_table('lift_logs')
    with op.batch_alter_table('workout_template_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_template_exercises_template_id'))
        batch_op.drop_index(batch_op.f('ix_workout_template_exercises_id'))

    op.drop_table('workout_template_exercises')
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_workout_sessions_id'))

    op.drop_table('workout_sessions')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_user_id'))
        batch_op.drop_index(batch_op.f('ix_goals_id'))

    op.drop_table('goals')
    with op.batch_alter_table('workout_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_templates_user_id'))
        batch_op.drop_index(batch_op.f('ix_workout_templates_share_id'))
        batch_op.drop_index(batch_op.f('ix_workout_templates_id'))

    op.drop_table('workout_templates')
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_id'))

    op.drop_table('push_subscriptions')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercises_name'))
        batch_op.drop_index(batch_op.f('ix_exercises_id'))

    op.drop_table('exercises')
    with op.batch_alter_table('calorie_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calorie_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_calorie_logs_id'))

    op.drop_table('calorie_logs')
    with op.batch_alter_table('body_weight_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_body_weight_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_body_weight_logs_id'))

    op.drop_table('body_weight_logs')
    with op.batch_alter_table('body_measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_body_measurements_user_id'))
        batch_op.drop_index(batch_op.f('ix_body_measurements_id'))

    op.drop_table('body_measurements')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
