from sqlalchemy.orm import Session

from . import models

# ---------------------------------------------------------------------------
# Exercise catalog
# Format: (name, category, muscle_group, secondary_muscle, equipment, difficulty, instructions)
#
# BODYWEIGHT EXERCISES: category = "bodyweight"
#   These are classified by reps only — no weight input needed.
#   Weighted variants (e.g. "Weighted Pull-up") are separate entries
#   with category = "compound" and use added weight for classification.
#
# UNILATERAL / DUMBBELL: weight logged is PER HAND.
#   Strength standards account for this — do NOT double the weight.
#
# SMITH MACHINE: slightly higher standards than free weight versions
#   because the machine guides the bar path (less stabilizer demand).
# ---------------------------------------------------------------------------

PREDEFINED_EXERCISES = [
    # ── ABS ─────────────────────────────────────────────────────────
    ("Ab Wheel Rollout", "compound", "abs", "shoulders", "ab wheel", "advanced",
     "Kneeling, roll the wheel forward as far as control allows while keeping the core braced, then roll back."),
    ("Barbell Rollout", "compound", "abs", "shoulders", "barbell", "advanced",
     "Kneeling with hands on a barbell, roll it forward as far as control allows, then roll back using the core."),
    ("Cable Crunch", "isolation", "abs", None, "cable", "beginner",
     "Kneeling below a high pulley, crunch your torso down toward your knees using the abs, not the arms."),
    ("Cable Woodchop (High to Low)", "isolation", "abs", "obliques", "cable", "intermediate",
     "With the pulley set high, pull the handle diagonally down and across your body using the obliques."),
    ("Cable Woodchop (Low to High)", "isolation", "abs", "obliques", "cable", "intermediate",
     "With the pulley set low, pull the handle diagonally up and across your body using the obliques."),
    ("Captain's Chair Leg Raise", "bodyweight", "abs", None, "machine", "intermediate",
     "Supported on forearm pads, raise your knees or legs up using the abs, then lower under control."),
    ("Copenhagen Plank", "isolation", "abs", "obliques", "bodyweight", "advanced",
     "With one foot on a bench and the opposite forearm on the floor, hold a side-plank position targeting the adductors and obliques."),
    ("Crunch", "isolation", "abs", None, "bodyweight", "beginner",
     "Lying on your back with knees bent, curl your shoulders off the floor by contracting the abs."),
    ("Dead Bug", "bodyweight", "abs", "core", "bodyweight", "beginner",
     "Lying on your back with arms and legs raised, slowly extend opposite arm and leg while keeping your lower back flat."),
    ("Hanging Knee Raise", "bodyweight", "abs", None, "pull-up bar", "intermediate",
     "Hanging from a bar, raise your knees toward your chest using the lower abs, then lower under control."),
    ("Hanging Leg Raise", "bodyweight", "abs", None, "pull-up bar", "advanced",
     "Hanging from a bar, raise your legs to hip height or higher using the lower abs, then lower under control."),
    ("Hollow Body Hold", "bodyweight", "abs", "core", "bodyweight", "intermediate",
     "Lying on your back, raise your shoulders and legs off the floor into a slight curve and hold the position."),
    ("Landmine Twist", "isolation", "abs", "obliques", "barbell", "intermediate",
     "With one end of a barbell anchored, rotate the free end from side to side using the core."),
    ("Machine Crunch", "isolation", "abs", None, "machine", "beginner",
     "Seated at the crunch machine, curl your torso forward against the resistance pad."),
    ("Med Ball Rotational Throw", "compound", "abs", "obliques", "medicine ball", "intermediate",
     "Rotate your torso and throw a medicine ball against a wall to develop rotational power."),
    ("Mountain Climber", "bodyweight", "abs", "core", "bodyweight", "beginner",
     "From a plank position, rapidly alternate driving your knees toward your chest."),
    ("Pallof Press", "isolation", "abs", "obliques", "cable", "intermediate",
     "Standing side-on to a cable, press the handle straight out from your chest and resist the rotational pull."),
    ("Plank", "bodyweight", "abs", "core", "bodyweight", "beginner",
     "Hold a straight-body position on your forearms and toes, bracing the core, for a set duration."),
    ("Reverse Crunch", "isolation", "abs", None, "bodyweight", "beginner",
     "Lying on your back, curl your hips off the floor by bringing your knees toward your chest."),
    ("Russian Twist", "isolation", "abs", "obliques", "plate", "beginner",
     "Seated with feet off the floor, rotate a weight from side to side while keeping the core engaged."),
    ("Side Plank", "bodyweight", "abs", "obliques", "bodyweight", "intermediate",
     "Balanced on one forearm and the side of one foot, hold a straight body line for time."),
    ("Sit-up", "isolation", "abs", None, "bodyweight", "beginner",
     "Lying on your back with knees bent, curl your entire torso up until seated, then lower under control."),
    ("Toes to Bar", "bodyweight", "abs", None, "pull-up bar", "advanced",
     "Hanging from a bar, raise your legs up to touch the bar using the lower abs and hip flexors."),
    ("V-Up", "bodyweight", "abs", None, "bodyweight", "intermediate",
     "Lying flat, simultaneously raise your legs and torso to touch your toes, forming a V shape."),
    ("Weighted Plank", "bodyweight", "abs", "core", "plate", "intermediate",
     "Hold a plank position with a weight plate placed on your upper back for added resistance."),
    ("Weighted Sit-up", "isolation", "abs", None, "plate", "intermediate",
     "Perform a sit-up while holding a weight plate against your chest for added resistance."),
    ("Woodchopper", "isolation", "abs", "obliques", "cable", "intermediate",
     "Using a high or low pulley, rotate your torso diagonally across your body against the cable's resistance."),

    # ── ADDUCTORS ───────────────────────────────────────────────────
    ("Adductor Machine", "isolation", "adductors", None, "machine", "beginner",
     "Seated at the adductor machine, squeeze your knees together against the resistance."),
    ("Cable Adduction", "isolation", "adductors", None, "cable", "beginner",
     "With an ankle cuff on a low cable, pull your leg across your body against the resistance."),
    ("Machine Adductor", "isolation", "adductors", None, "machine", "beginner",
     "Seated at the adductor machine, squeeze your knees together against the resistance."),

    # ── BACK ────────────────────────────────────────────────────────
    ("Back Extension", "isolation", "back", "glutes, hamstrings", "bodyweight", "beginner",
     "On a hyperextension bench, lower your torso forward and extend back up using the lower back and glutes."),
    ("Barbell Row", "compound", "back", "biceps", "barbell", "intermediate",
     "Hinge at the hips with a flat back and row the bar to your lower ribcage, squeezing the shoulder blades together."),
    ("Chest-Supported Row", "compound", "back", "biceps", "machine", "beginner",
     "With your chest braced against a pad, row the handles toward you, isolating the back without lower-back strain."),
    ("Chin-up", "bodyweight", "back", "biceps", "pull-up bar", "intermediate",
     "Hang from a bar with an underhand grip and pull your chin above the bar, emphasizing the biceps more than a pull-up."),
    ("Close-Grip Lat Pulldown", "isolation", "back", "biceps", "cable", "beginner",
     "Using a close, neutral-grip handle, pull the bar down to your upper chest, leaning back slightly."),
    ("Deadlift", "compound", "back", "hamstrings, glutes", "barbell", "advanced",
     "Grip the bar just outside your legs, keep a flat back, and drive through the floor to stand fully upright."),
    ("Deficit Deadlift", "compound", "back", "hamstrings, glutes", "barbell", "advanced",
     "Standing on a small platform, deadlift the bar through a longer range of motion than a standard pull."),
    ("Dumbbell Shrug", "isolation", "back", "traps", "dumbbell", "beginner",
     "Holding dumbbells at your sides, shrug your shoulders straight up and squeeze at the top."),
    ("Face Pull", "isolation", "back", "shoulders", "cable", "beginner",
     "Pull a rope attachment toward your face, flaring the elbows out and squeezing the rear delts and upper back."),
    ("Good Morning", "compound", "back", "hamstrings, glutes", "barbell", "advanced",
     "With the bar on your upper back, hinge forward at the hips keeping a flat back, then return to standing."),
    ("Inverted Row", "bodyweight", "back", "biceps", "barbell", "beginner",
     "Lying under a bar set at hip height, pull your chest to the bar while keeping your body straight."),
    ("Jefferson Curl", "isolation", "back", "hamstrings", "barbell", "advanced",
     "Standing on a raised platform, slowly round your spine forward vertebra by vertebra while holding a light weight."),
    ("Landmine Row", "compound", "back", "biceps", "barbell", "intermediate",
     "With one end of a barbell anchored, row the free end up toward your torso."),
    ("Lat Pulldown", "isolation", "back", "biceps", "cable", "beginner",
     "With a wide overhand grip, pull the bar down to your upper chest and control it back to full stretch."),
    ("Machine Assisted Pull-up", "bodyweight", "back", "biceps", "machine", "beginner",
     "Using a counterweighted assist machine, perform pull-ups with reduced bodyweight resistance."),
    ("Machine Row", "isolation", "back", "biceps", "machine", "beginner",
     "Sit at the row machine and pull the handles toward your torso, squeezing the shoulder blades at the finish."),
    ("Meadows Row", "compound", "back", "biceps", "barbell", "intermediate",
     "Using a landmine setup and a single-arm grip, row the bar up and back in a slightly rotated path."),
    ("Neutral-Grip Pull-up", "bodyweight", "back", "biceps", "pull-up bar", "intermediate",
     "Using parallel handles, pull your chin above the bar with palms facing each other."),
    ("One-Arm Dumbbell Row", "compound", "back", "biceps", "dumbbell", "beginner",
     "With one knee and hand on a bench, row a dumbbell up to your hip, keeping the torso still."),
    ("Pendlay Row", "compound", "back", "biceps", "barbell", "advanced",
     "From a dead stop on the floor each rep, explosively row the bar to the lower chest with a flat torso."),
    ("Pull-up", "bodyweight", "back", "biceps", "pull-up bar", "intermediate",
     "Hang from a bar with an overhand grip and pull your chin above the bar, then lower under control."),
    ("Rack Pull", "compound", "back", "hamstrings", "barbell", "intermediate",
     "Set the bar on pins just below knee height and pull to lockout, emphasizing the top portion of the deadlift."),
    ("Renegade Row", "compound", "back", "core", "dumbbell", "intermediate",
     "In a plank position with hands on dumbbells, row one dumbbell at a time while resisting torso rotation."),
    ("Seal Row", "compound", "back", "biceps", "barbell", "intermediate",
     "Lying face-down on an elevated bench, row a bar up to your chest, removing lower-back involvement."),
    ("Seated Cable Row", "isolation", "back", "biceps", "cable", "beginner",
     "Sit upright and pull the handle toward your torso, squeezing your shoulder blades together at the finish."),
    ("Shrug", "isolation", "back", "traps", "barbell", "beginner",
     "Holding a bar or dumbbells at your sides, elevate your shoulders straight up toward your ears, then lower."),
    ("Single-Arm Lat Pulldown", "isolation", "back", "biceps", "cable", "intermediate",
     "Using a single handle, pull down and back on one side at a time to address side-to-side imbalances."),
    ("Snatch-Grip Deadlift", "compound", "back", "hamstrings, traps", "barbell", "advanced",
     "Using a wide, snatch-width grip, deadlift the bar through an extended range of motion."),
    ("Straight-Arm Pulldown", "isolation", "back", None, "cable", "beginner",
     "With arms nearly straight, pull the bar down from overhead to your thighs, focusing on the lats."),
    ("Sumo Deadlift", "compound", "back", "glutes, hamstrings", "barbell", "advanced",
     "With a wide stance and hands inside the knees, drive the floor away while keeping the torso more upright than a conventional pull."),
    ("T-Bar Row", "compound", "back", "biceps", "barbell", "intermediate",
     "Straddle the bar, grip the handles, and row the weight to your chest while keeping the back flat."),
    ("Trap Bar Deadlift", "compound", "back", "quads, glutes", "trap bar", "intermediate",
     "Standing inside a trap bar, grip the handles and drive through the floor to stand upright, more quad-dominant than a straight bar."),
    ("Weighted Chin-up", "compound", "back", "biceps", "pull-up bar", "advanced",
     "Perform a chin-up with added weight via a belt or vest for increased resistance."),
    ("Weighted Pull-up", "compound", "back", "biceps", "pull-up bar", "advanced",
     "Perform a pull-up with added weight via a belt or vest for increased resistance."),
    ("Wide-Grip Cable Row", "isolation", "back", None, "cable", "intermediate",
     "Using a wide bar attachment, row toward the upper abdomen to emphasize the upper back and rear delts."),

    # ── BICEPS ──────────────────────────────────────────────────────
    ("21s", "isolation", "biceps", None, "barbell", "advanced",
     "Perform 7 half-reps from the bottom to midpoint, 7 half-reps from midpoint to top, then 7 full reps."),
    ("Alternating Dumbbell Curl", "isolation", "biceps", "forearms", "dumbbell", "beginner",
     "Curl one dumbbell at a time, alternating arms, allowing a slight rotation of the wrist."),
    ("Barbell Curl", "isolation", "biceps", "forearms", "barbell", "beginner",
     "Standing, curl the bar from full extension up to shoulder height, keeping elbows pinned at your sides."),
    ("Bayesian Cable Curl", "isolation", "biceps", "forearms", "cable", "intermediate",
     "Standing in front of a low cable with the arm behind the torso, curl the handle up for a deep stretch position."),
    ("Bicep Curl", "isolation", "biceps", "forearms", "dumbbell", "beginner",
     "Curl a dumbbell or barbell from full extension to shoulder height, keeping the elbows still."),
    ("Cable Curl", "isolation", "biceps", "forearms", "cable", "beginner",
     "Using a straight bar or rope attachment, curl the cable up while keeping constant tension throughout."),
    ("Cable Rope Hammer Curl", "isolation", "biceps", "forearms", "cable", "beginner",
     "Using a rope attachment, curl with palms facing each other for a hammer-curl style movement."),
    ("Close-Grip Barbell Curl", "isolation", "biceps", "forearms", "barbell", "beginner",
     "Using a grip narrower than shoulder-width, curl the bar up to emphasize the long head of the biceps."),
    ("Concentration Curl", "isolation", "biceps", None, "dumbbell", "beginner",
     "Seated, brace your elbow against your inner thigh and curl a dumbbell up with strict form."),
    ("Cross-Body Hammer Curl", "isolation", "biceps", "forearms", "dumbbell", "beginner",
     "Curl a dumbbell across your body toward the opposite shoulder with palm facing in."),
    ("Drag Curl", "isolation", "biceps", None, "barbell", "intermediate",
     "Curl the bar close along your torso, keeping elbows behind the body throughout the movement."),
    ("Dumbbell Curl", "isolation", "biceps", "forearms", "dumbbell", "beginner",
     "Curl a dumbbell in each hand from full extension to shoulder height, keeping elbows still."),
    ("EZ Bar Curl", "isolation", "biceps", "forearms", "barbell", "beginner",
     "Using an EZ-curl bar's angled grip, curl the weight up with reduced wrist strain compared to a straight bar."),
    ("EZ-Bar Curl", "isolation", "biceps", "forearms", "barbell", "beginner",
     "Using an EZ-curl bar's angled grip, curl the weight up with reduced wrist strain compared to a straight bar."),
    ("Hammer Curl", "isolation", "biceps", "forearms", "dumbbell", "beginner",
     "Curl dumbbells with palms facing each other throughout, emphasizing the brachialis and forearms."),
    ("Incline Dumbbell Curl", "isolation", "biceps", None, "dumbbell", "intermediate",
     "Seated on an incline bench with arms hanging back, curl the dumbbells to get a deeper stretch on the biceps."),
    ("Preacher Curl", "isolation", "biceps", None, "barbell", "intermediate",
     "With your arm braced against a preacher pad, curl the weight up, isolating the biceps and limiting momentum."),
    ("Preacher Curl (Dumbbell)", "isolation", "biceps", None, "dumbbell", "intermediate",
     "Using a preacher pad and a single dumbbell, curl one arm at a time for a strict, isolated contraction."),
    ("Scott Curl", "isolation", "biceps", None, "dumbbell", "intermediate",
     "Using a preacher-style bench with a single dumbbell, curl with strict form to isolate the biceps."),
    ("Spider Curl", "isolation", "biceps", None, "barbell", "intermediate",
     "Lying chest-down on an incline bench, curl the weight up with arms hanging freely for strict isolation."),
    ("Wide-Grip Barbell Curl", "isolation", "biceps", None, "barbell", "beginner",
     "Using a grip wider than shoulder-width, curl the bar up to emphasize the short head of the biceps."),
    ("Zottman Curl", "isolation", "biceps", "forearms", "dumbbell", "intermediate",
     "Curl the dumbbells up with palms facing up, then rotate palms down and lower slowly to work the forearms."),

    # ── CALVES ──────────────────────────────────────────────────────
    ("Calf Raise", "isolation", "calves", None, "bodyweight", "beginner",
     "Rise up onto the balls of your feet as high as possible, then lower under control for a full stretch."),
    ("Calf Raise on Leg Press", "isolation", "calves", None, "machine", "beginner",
     "Positioned on the balls of your feet on the leg press platform, extend the ankles against the resistance."),
    ("Donkey Calf Raise", "isolation", "calves", None, "machine", "intermediate",
     "Bent forward at the hips with weight loaded on your lower back, raise your heels using only the ankles."),
    ("Jump Rope", "bodyweight", "calves", "cardio", "jump rope", "beginner",
     "Skip continuously over a rope for time, staying light on the balls of the feet."),
    ("Leg Press Calf Raise", "isolation", "calves", None, "machine", "beginner",
     "On the leg press machine, push through the balls of your feet to extend the ankles against the platform."),
    ("Seated Calf Raise", "isolation", "calves", None, "machine", "beginner",
     "Seated with the pad on your knees, raise your heels by extending the ankles, targeting the soleus."),
    ("Single-Leg Calf Raise", "isolation", "calves", None, "bodyweight", "beginner",
     "Standing on one foot, rise onto the ball of your foot and lower under control to address imbalances."),
    ("Standing Calf Raise", "isolation", "calves", None, "machine", "beginner",
     "Standing on the balls of your feet, rise up as high as possible then lower under control for a full stretch."),

    # ── CHEST ───────────────────────────────────────────────────────
    ("Bench Press", "compound", "chest", "triceps, shoulders", "barbell", "intermediate",
     "Lie on a flat bench, grip the bar just wider than shoulder-width, lower it to mid-chest, then press back up to lockout."),
    ("Cable Chest Press", "compound", "chest", "triceps", "cable", "beginner",
     "Standing between two cable stacks at chest height, press the handles forward to full extension."),
    ("Cable Crossover (High to Low)", "isolation", "chest", None, "cable", "intermediate",
     "With pulleys set high, bring the handles down and together in front of your hips."),
    ("Cable Crossover (Low to High)", "isolation", "chest", None, "cable", "intermediate",
     "With pulleys set low, bring the handles up and together above your head."),
    ("Cable Fly", "isolation", "chest", None, "cable", "beginner",
     "Standing between two cable stacks set at chest height, bring the handles together in front of you in an arcing motion."),
    ("Chest Press Machine (Single Arm)", "compound", "chest", "triceps", "machine", "beginner",
     "Press one handle at a time on the chest press machine to address side-to-side imbalances."),
    ("Decline Bench Press", "compound", "chest", "triceps", "barbell", "intermediate",
     "On a decline bench, lower the bar to the lower chest and press up, targeting the lower chest fibers."),
    ("Decline Cable Fly", "isolation", "chest", None, "cable", "intermediate",
     "Seated on a decline bench with high cable pulleys, bring the handles down and together over the chest."),
    ("Decline Dumbbell Press", "compound", "chest", "triceps", "dumbbell", "intermediate",
     "On a decline bench, press dumbbells up from chest level, targeting the lower chest."),
    ("Dip", "bodyweight", "chest", "triceps", "dip bar", "intermediate",
     "Lower your body between parallel bars, leaning forward slightly to bias the chest, then press back to the top."),
    ("Dumbbell Bench Press", "compound", "chest", "triceps, shoulders", "dumbbell", "beginner",
     "Press a dumbbell in each hand from chest level to full extension above the chest, allowing a deeper stretch than a barbell."),
    ("Dumbbell Fly", "isolation", "chest", None, "dumbbell", "beginner",
     "Lying flat with a slight elbow bend, lower the dumbbells out to the sides in an arc, then bring them back together."),
    ("Flat Dumbbell Fly", "isolation", "chest", None, "dumbbell", "beginner",
     "Lying flat with a slight elbow bend, lower the dumbbells out to the sides in an arc, then bring them back together over the chest."),
    ("High Cable Fly", "isolation", "chest", None, "cable", "intermediate",
     "With pulleys set high, bring the handles downward and inward to target the lower chest."),
    ("Incline Bench Press", "compound", "chest", "shoulders, triceps", "barbell", "intermediate",
     "On an incline bench (30-45 degrees), lower the bar to the upper chest and press up, keeping elbows at roughly a 45-degree angle."),
    ("Incline Cable Fly", "isolation", "chest", None, "cable", "intermediate",
     "Seated on an incline bench between low cable pulleys, bring the handles up and together over the chest."),
    ("Incline Dumbbell Fly", "isolation", "chest", None, "dumbbell", "intermediate",
     "On an incline bench, perform the same arcing motion as a flat fly to emphasize the upper chest."),
    ("Incline Dumbbell Press", "compound", "chest", "shoulders, triceps", "dumbbell", "intermediate",
     "On an incline bench, press dumbbells from shoulder level to overhead, focusing on the upper chest."),
    ("Incline Machine Press", "compound", "chest", "shoulders", "machine", "beginner",
     "Sit at an incline press machine and push the handles upward and forward to target the upper chest."),
    ("Landmine Press", "compound", "chest", "shoulders", "barbell", "intermediate",
     "With one end of a barbell anchored, press the free end up and forward from shoulder height."),
    ("Low Cable Fly", "isolation", "chest", None, "cable", "intermediate",
     "With pulleys set low, bring the handles upward and inward to target the upper chest."),
    ("Machine Assisted Dip", "bodyweight", "chest", "triceps", "machine", "beginner",
     "Using a counterweighted assist machine, perform dips with reduced bodyweight resistance."),
    ("Machine Chest Press", "compound", "chest", "triceps", "machine", "beginner",
     "Sit at the chest press machine and press the handles forward to full extension, then return under control."),
    ("Pause Bench Press", "compound", "chest", "triceps", "barbell", "advanced",
     "Perform a bench press with a 2-3 second pause at the chest before pressing back up, removing the stretch reflex."),
    ("Pec Deck", "isolation", "chest", None, "machine", "beginner",
     "Sit with elbows against the pads and bring your arms together in front of your chest, squeezing at the peak."),
    ("Push-up", "bodyweight", "chest", "triceps, shoulders", "bodyweight", "beginner",
     "From a plank position, lower your chest to the floor keeping the body straight, then press back up."),
    ("Single-Arm Cable Chest Press", "compound", "chest", "core", "cable", "intermediate",
     "Press one handle forward at a time, resisting rotation of the torso for added core engagement."),
    ("Smith Machine Bench Press", "compound", "chest", "triceps, shoulders", "smith machine", "beginner",
     "Perform a bench press on the Smith machine's fixed bar path, unracking with a slight twist to unlock."),
    ("Smith Machine Incline Press", "compound", "chest", "shoulders", "smith machine", "beginner",
     "Set an incline bench under the Smith bar and press through the fixed vertical path."),
    ("Svend Press", "isolation", "chest", None, "plate", "beginner",
     "Press a weight plate between both palms out in front of the chest, squeezing the plate throughout the movement."),
    ("Weighted Dip", "compound", "chest", "triceps, shoulders", "dip bar", "advanced",
     "With added weight via belt or vest, lower your body between parallel bars until a stretch is felt in the chest, then press back up."),
    ("Weighted Push-up", "compound", "chest", "triceps, shoulders", "bodyweight", "intermediate",
     "Perform a standard push-up with a plate or vest added for resistance."),

    # ── ABS ────────────────────────────────────────────────────────
    ("Bear Crawl", "bodyweight", "abs", "shoulders", "bodyweight", "beginner",
     "On hands and feet with knees hovering off the floor, crawl forward while keeping the hips level."),
    ("Suitcase Carry", "compound", "abs", "forearms", "dumbbell", "intermediate",
     "Carry a weight in one hand at your side, keeping the torso upright to resist lateral flexion."),
    ("Zercher Carry", "compound", "abs", "biceps", "barbell", "advanced",
     "Cradling a loaded barbell in the crooks of your elbows, walk for distance while keeping the torso braced."),

    # ── FOREARMS ────────────────────────────────────────────────────
    ("Dead Hang", "bodyweight", "forearms", "back", "pull-up bar", "beginner",
     "Hang from a pull-up bar with arms fully extended, holding for time to build grip endurance."),
    ("Farmer's Carry", "compound", "forearms", "traps, core", "dumbbell", "beginner",
     "Carry a heavy dumbbell or kettlebell in each hand for distance or time, keeping the torso upright."),
    ("Farmer's Walk (Single Arm)", "compound", "forearms", "core", "dumbbell", "intermediate",
     "Carry a heavy dumbbell in one hand for distance, resisting the urge to lean, to challenge grip and core stability."),
    ("Plate Pinch Hold", "isolation", "forearms", None, "plate", "intermediate",
     "Pinch two weight plates together between your fingers and thumb, holding for time to build grip strength."),
    ("Reverse Curl", "isolation", "forearms", "biceps", "barbell", "intermediate",
     "Using an overhand grip, curl the bar up, targeting the forearms and brachialis more than a standard curl."),
    ("Reverse Wrist Curl", "isolation", "forearms", None, "barbell", "beginner",
     "With palms facing down, extend the wrists upward against the resistance of the bar."),
    ("Wrist Curl", "isolation", "forearms", None, "barbell", "beginner",
     "Resting your forearms on a bench with wrists hanging off the edge, curl the bar up using only wrist motion."),

    # ── FULL BODY ───────────────────────────────────────────────────
    ("Assault Bike Sprint", "bodyweight", "full body", "cardio", "bike", "beginner",
     "Pedal an air/fan bike at maximum effort for a short interval to build conditioning."),
    ("Box Jump", "bodyweight", "full body", "quads, glutes", "box", "intermediate",
     "From a quarter-squat, explosively jump onto a box, landing softly with both feet."),
    ("Broad Jump", "bodyweight", "full body", "quads, glutes", "bodyweight", "intermediate",
     "From a quarter-squat, jump forward for maximum horizontal distance, landing softly."),
    ("Burpee", "bodyweight", "full body", "core", "bodyweight", "intermediate",
     "Drop into a push-up, then explosively jump up, combining a squat, plank, push-up, and jump."),
    ("Clean and Jerk", "compound", "full body", "legs, shoulders", "barbell", "advanced",
     "Clean the bar to the shoulders, then drive it overhead with a leg dip and split-stance catch."),
    ("Hang Clean", "compound", "full body", "legs, back, shoulders", "barbell", "advanced",
     "From a hang position at the knees, explosively pull the bar up and catch it at the shoulders."),
    ("Kettlebell Clean", "compound", "full body", "shoulders, back", "kettlebell", "intermediate",
     "Explosively pull a kettlebell from between your legs up to a racked position at the shoulder."),
    ("Kettlebell Snatch", "compound", "full body", "shoulders, back", "kettlebell", "advanced",
     "Explosively pull a kettlebell from between your legs to an overhead lockout in one motion."),
    ("Kettlebell Swing", "compound", "full body", "glutes, hamstrings", "kettlebell", "intermediate",
     "Hinge at the hips to swing the kettlebell between your legs, then drive your hips forward to swing it to chest height."),
    ("Med Ball Slam", "compound", "full body", "abs, shoulders", "medicine ball", "beginner",
     "Raise a medicine ball overhead and slam it into the ground as hard as possible, then reset."),
    ("Power Clean", "compound", "full body", "legs, back, shoulders", "barbell", "advanced",
     "Pull the bar explosively from the floor and catch it at the shoulders in a partial squat, then stand up."),
    ("Rowing Machine Sprint", "bodyweight", "full body", "back, legs", "rowing machine", "beginner",
     "Row at maximum effort for a short interval, driving with the legs before pulling with the arms."),
    ("Sled Pull", "compound", "full body", "back, hamstrings", "sled", "intermediate",
     "Pull a weighted sled toward you by walking backward or using a rope in a hand-over-hand motion."),
    ("Sled Push", "compound", "full body", "quads, glutes", "sled", "intermediate",
     "Drive a weighted sled forward using powerful leg strides while keeping the torso braced."),
    ("Snatch", "compound", "full body", "legs, back, shoulders", "barbell", "advanced",
     "Pull the bar from the floor to overhead in one continuous motion, catching it in a deep squat."),
    ("Thruster", "compound", "full body", "quads, shoulders", "barbell", "advanced",
     "Combine a front squat with an overhead press in one fluid motion, driving up out of the squat into the press."),
    ("Turkish Get-up", "compound", "full body", "shoulders, core", "kettlebell", "advanced",
     "Starting lying down with a weight overhead, work through a series of steps to stand up while keeping the arm locked out."),

    # ── GLUTES ──────────────────────────────────────────────────────
    ("Banded Hip Thrust", "compound", "glutes", "hamstrings", "resistance band", "beginner",
     "With a band around your hips and upper back on a bench, drive your hips up against the added resistance."),
    ("Barbell Glute Bridge", "compound", "glutes", "hamstrings", "barbell", "beginner",
     "Lying on the floor with the bar over your hips, drive up into a bridge, squeezing the glutes at the top."),
    ("Barbell Hip Thrust (Banded)", "compound", "glutes", "hamstrings", "barbell", "intermediate",
     "Perform a standard hip thrust with a resistance band around the knees to add glute medius activation."),
    ("Cable Hip Abduction", "isolation", "glutes", None, "cable", "beginner",
     "With an ankle cuff attached to a low cable, raise your leg out to the side against the resistance."),
    ("Cable Kickback", "isolation", "glutes", None, "cable", "beginner",
     "With an ankle cuff attached to a low cable, kick your leg back and up, squeezing the glute at the top."),
    ("Cable Pull-Through", "compound", "glutes", "hamstrings", "cable", "beginner",
     "Facing away from a low cable, hinge at the hips and pull the rope through your legs, then stand up squeezing the glutes."),
    ("Curtsy Lunge", "compound", "glutes", "quads", "dumbbell", "intermediate",
     "Step one leg diagonally behind the other into a lunge, then return to standing, targeting the glute medius."),
    ("Frog Pump", "isolation", "glutes", None, "bodyweight", "beginner",
     "Lying on your back with soles of your feet together, drive your hips up and squeeze the glutes at the top."),
    ("Hip Abduction Machine", "isolation", "glutes", None, "machine", "beginner",
     "Seated at the machine, push your knees outward against the pads to target the glute medius."),
    ("Hip Thrust", "compound", "glutes", "hamstrings", "barbell", "intermediate",
     "With your upper back on a bench and the bar over your hips, drive through your heels to full hip extension."),
    ("Single-Leg Hip Thrust", "compound", "glutes", "hamstrings", "bodyweight", "intermediate",
     "With one foot on the floor and the other extended, drive your hips up using a single leg."),
    ("Smith Machine Hip Thrust", "compound", "glutes", "hamstrings", "smith machine", "beginner",
     "With your upper back on a bench and the Smith bar over your hips, drive up into a bridge along the fixed path."),

    # ── HAMSTRINGS ──────────────────────────────────────────────────
    ("Dumbbell Romanian Deadlift", "compound", "hamstrings", "glutes", "dumbbell", "beginner",
     "Using dumbbells, hinge at the hips keeping a flat back until you feel a hamstring stretch, then return to standing."),
    ("Glute-Ham Raise", "bodyweight", "hamstrings", "glutes", "GHD", "advanced",
     "On a GHD machine, lower your torso forward under control and pull back up using the hamstrings and glutes."),
    ("Leg Curl", "isolation", "hamstrings", None, "machine", "beginner",
     "Curl the pad toward your glutes by bending the knees, then lower under control."),
    ("Lying Leg Curl", "isolation", "hamstrings", None, "machine", "beginner",
     "Lying face down, curl the pad up toward your glutes by bending the knees, then lower under control."),
    ("Nordic Curl", "bodyweight", "hamstrings", None, "bodyweight", "advanced",
     "With your ankles anchored, lower your torso forward as slowly as possible using only the hamstrings, then push back up."),
    ("Romanian Deadlift", "compound", "hamstrings", "glutes, back", "barbell", "intermediate",
     "With a slight knee bend, hinge at the hips and lower the bar along your legs until a stretch is felt, then stand back up."),
    ("Seated Leg Curl", "isolation", "hamstrings", None, "machine", "beginner",
     "Seated with the pad against your lower shins, curl your legs back and down, then return to the start."),
    ("Single-Leg Romanian Deadlift", "compound", "hamstrings", "glutes", "dumbbell", "intermediate",
     "Balancing on one leg, hinge forward while extending the other leg back, then return to standing."),
    ("Standing Leg Curl", "isolation", "hamstrings", None, "machine", "beginner",
     "Standing at the machine, curl one leg back toward your glutes, then lower under control."),
    ("Stiff-Leg Deadlift", "compound", "hamstrings", "back", "barbell", "advanced",
     "With minimal knee bend, hinge forward at the hips to lower the bar, emphasizing the hamstrings."),

    # ── HIP FLEXORS ─────────────────────────────────────────────────
    ("Standing Hip Flexor Raise", "isolation", "hip flexors", None, "cable", "beginner",
     "With an ankle cuff on a low cable, raise your knee up toward your chest against the resistance."),

    # ── NECK ────────────────────────────────────────────────────────
    ("Lateral Neck Flexion", "isolation", "neck", None, "bodyweight", "beginner",
     "Lying on your side, lower and raise your head sideways against gravity or light manual resistance."),
    ("Neck Curl", "isolation", "neck", None, "plate", "beginner",
     "Lying on your back with a plate on your forehead, curl your chin toward your chest against the resistance."),
    ("Neck Extension", "isolation", "neck", None, "plate", "beginner",
     "Lying face down with a plate against the back of your head, extend your neck upward against the resistance."),

    # ── QUADS ───────────────────────────────────────────────────────
    ("Back Squat", "compound", "quads", "glutes, hamstrings", "barbell", "advanced",
     "With the bar on your upper back, squat down until thighs are at least parallel, then drive back up."),
    ("Barbell Lunge", "compound", "quads", "glutes", "barbell", "intermediate",
     "With the bar on your upper back, step forward into a lunge and return, alternating legs."),
    ("Belt Squat", "compound", "quads", "glutes", "machine", "intermediate",
     "With weight suspended from a belt around your hips, squat down and back up without loading the spine."),
    ("Box Squat", "compound", "quads", "glutes", "barbell", "intermediate",
     "Squat down and lightly touch a box behind you before driving back up, helping build depth control."),
    ("Bulgarian Split Squat", "compound", "quads", "glutes", "dumbbell", "intermediate",
     "With your rear foot elevated on a bench, lower into a lunge on the front leg, then drive back up."),
    ("Cyclist Squat", "compound", "quads", "glutes", "barbell", "intermediate",
     "With heels elevated on plates, squat deep to emphasize the quads over the posterior chain."),
    ("Front Squat", "compound", "quads", "glutes, core", "barbell", "advanced",
     "With the bar racked across the front shoulders, squat down keeping the torso upright, then stand back up."),
    ("Goblet Squat", "compound", "quads", "glutes", "dumbbell", "beginner",
     "Holding a dumbbell close to your chest, squat down between your knees and stand back up."),
    ("Hack Squat", "compound", "quads", "glutes", "machine", "intermediate",
     "On a hack squat machine, lower your body by bending the knees, then press back up along the fixed path."),
    ("Kettlebell Goblet Reverse Lunge", "compound", "quads", "glutes", "kettlebell", "beginner",
     "Holding a kettlebell at your chest, step backward into a lunge and return to standing."),
    ("Leg Extension", "isolation", "quads", None, "machine", "beginner",
     "Sit at the leg extension machine and extend your knees to lift the pad, then lower under control."),
    ("Leg Press", "compound", "quads", "glutes, hamstrings", "machine", "beginner",
     "Push the platform away by extending your knees and hips, then lower under control back toward your chest."),
    ("Leg Press (Single Leg)", "compound", "quads", "glutes", "machine", "intermediate",
     "Press the platform using one leg at a time to address strength imbalances."),
    ("Overhead Squat", "compound", "quads", "shoulders, core", "barbell", "advanced",
     "With the bar locked out overhead, squat down while keeping the arms extended and torso upright."),
    ("Pause Squat", "compound", "quads", "glutes", "barbell", "advanced",
     "Perform a squat with a 2-3 second pause at the bottom before standing, building strength out of the hole."),
    ("Pistol Squat", "bodyweight", "quads", "glutes, core", "bodyweight", "advanced",
     "Balancing on one leg, squat down as low as possible while keeping the other leg extended forward."),
    ("Reverse Lunge", "compound", "quads", "glutes", "dumbbell", "beginner",
     "Step backward into a lunge, lowering the back knee toward the floor, then return to standing."),
    ("Sissy Squat", "isolation", "quads", None, "bodyweight", "advanced",
     "Leaning back while rising onto your toes, bend only at the knees to lower your torso, then return up."),
    ("Sled Drag (Reverse)", "compound", "quads", "core", "sled", "intermediate",
     "Facing a weighted sled, walk backward pulling the straps toward you to heavily tax the quads."),
    ("Smith Machine Lunge", "compound", "quads", "glutes", "smith machine", "beginner",
     "Perform a lunge with the fixed bar path of the Smith machine for added stability."),
    ("Smith Machine Squat", "compound", "quads", "glutes", "smith machine", "beginner",
     "Squat down and back up along the Smith machine's fixed vertical bar path."),
    ("Squat", "compound", "quads", "glutes, hamstrings", "barbell", "advanced",
     "With the bar on your upper back, squat down until thighs are at least parallel, then drive back up."),
    ("Static Lunge", "compound", "quads", "glutes", "dumbbell", "beginner",
     "From a fixed split stance, lower the back knee toward the floor and drive back up without stepping."),
    ("Step-up", "compound", "quads", "glutes", "dumbbell", "beginner",
     "Step onto a bench or box with one leg, driving through the heel to stand fully, then step back down."),
    ("Walking Lunge", "compound", "quads", "glutes", "dumbbell", "beginner",
     "Step forward into a lunge, lowering the back knee toward the floor, then push off into the next step."),
    ("Walking Lunges", "compound", "quads", "glutes", "dumbbell", "beginner",
     "Step forward into a lunge, lowering the back knee toward the floor, then push off into the next step."),
    ("Wall Sit", "bodyweight", "quads", None, "bodyweight", "beginner",
     "With your back against a wall, hold a seated position with knees at 90 degrees for time."),
    ("Weighted Step-up", "compound", "quads", "glutes", "dumbbell", "intermediate",
     "Holding dumbbells, step onto a bench or box with one leg and drive through the heel to stand."),
    ("Zercher Squat", "compound", "quads", "core, back", "barbell", "advanced",
     "Cradling the bar in the crooks of your elbows, squat down and back up, heavily taxing the core."),

    # ── SHOULDERS ───────────────────────────────────────────────────
    ("Arnold Press", "compound", "shoulders", "triceps", "dumbbell", "intermediate",
     "Start with palms facing you at shoulder height, rotate as you press overhead so palms face forward at the top."),
    ("Band Pull-Apart", "isolation", "shoulders", "back", "resistance band", "beginner",
     "Holding a band at shoulder height with arms extended, pull it apart by squeezing the shoulder blades together."),
    ("Banded Lateral Raise", "isolation", "shoulders", None, "resistance band", "beginner",
     "Standing on a band, raise your arms out to the sides against the resistance to shoulder height."),
    ("Battle Ropes", "isolation", "shoulders", "core", "battle ropes", "intermediate",
     "Alternate slamming heavy ropes up and down as fast as possible while keeping a stable athletic stance."),
    ("Behind-the-Neck Press", "compound", "shoulders", "triceps", "barbell", "advanced",
     "Press the bar overhead from behind the neck, requiring good shoulder mobility."),
    ("Cable Front Raise", "isolation", "shoulders", None, "cable", "beginner",
     "With the cable set low behind you, raise the handle out in front to shoulder height."),
    ("Cable Lateral Raise", "isolation", "shoulders", None, "cable", "beginner",
     "With the cable set low, raise the handle out to the side to shoulder height for constant tension."),
    ("Cable Rear Delt Fly", "isolation", "shoulders", "back", "cable", "intermediate",
     "Using crossed cables at chest height, pull the handles out and back to target the rear delts."),
    ("Cable Reverse Fly", "isolation", "shoulders", "back", "cable", "intermediate",
     "Using crossed cable handles, pull your arms out and back to target the rear delts."),
    ("Cable Upright Row", "compound", "shoulders", "traps", "cable", "intermediate",
     "Using a straight bar attachment, pull the cable up along your body to chest height."),
    ("Cuban Press", "compound", "shoulders", "back", "dumbbell", "intermediate",
     "Combine an upright row, external rotation, and overhead press into one continuous movement for shoulder health."),
    ("Dumbbell Lateral Raise", "isolation", "shoulders", None, "dumbbell", "beginner",
     "Raise dumbbells out to the sides to shoulder height with a slight elbow bend, then lower under control."),
    ("Dumbbell Shoulder Press", "compound", "shoulders", "triceps", "dumbbell", "beginner",
     "Press dumbbells from shoulder height to overhead lockout, seated or standing."),
    ("Front Raise", "isolation", "shoulders", None, "dumbbell", "beginner",
     "Raise a dumbbell or plate straight out in front to shoulder height, then lower under control."),
    ("Lateral Raise", "isolation", "shoulders", None, "dumbbell", "beginner",
     "Raise dumbbells out to the sides to shoulder height with a slight elbow bend, then lower under control."),
    ("Machine Lateral Raise", "isolation", "shoulders", None, "machine", "beginner",
     "Sit at the lateral raise machine and push the pads out to the sides to shoulder height."),
    ("Machine Shoulder Press", "compound", "shoulders", "triceps", "machine", "beginner",
     "Sit at the shoulder press machine and press the handles straight up to full extension."),
    ("Overhead Press", "compound", "shoulders", "triceps", "barbell", "intermediate",
     "Press the bar from shoulder height straight overhead to full lockout, keeping the core braced."),
    ("Push Press", "compound", "shoulders", "triceps, legs", "barbell", "advanced",
     "Use a slight leg dip and drive to help press the bar overhead, allowing heavier loads than a strict press."),
    ("Rear Delt Fly", "isolation", "shoulders", "back", "dumbbell", "beginner",
     "Bent forward at the hips, raise dumbbells out to the sides, squeezing the rear delts and upper back."),
    ("Reverse Pec Deck", "isolation", "shoulders", "back", "machine", "beginner",
     "Facing the pec deck machine, pull the handles backward and out to target the rear delts."),
    ("Seated Dumbbell Press", "compound", "shoulders", "triceps", "dumbbell", "beginner",
     "Seated with back support, press dumbbells from shoulder height to overhead lockout."),
    ("Single-Arm Landmine Press", "compound", "shoulders", "triceps, core", "barbell", "intermediate",
     "With one end of a barbell anchored, press the free end up and forward using a single arm."),
    ("Smith Machine OHP", "compound", "shoulders", "triceps", "smith machine", "beginner",
     "Press the Smith bar straight overhead along its fixed vertical path."),
    ("Smith Machine Shoulder Press", "compound", "shoulders", "triceps", "smith machine", "beginner",
     "Seated under the Smith bar, press straight up along the fixed vertical path."),
    ("Standing Dumbbell Press", "compound", "shoulders", "triceps, core", "dumbbell", "intermediate",
     "Standing, press dumbbells overhead while bracing the core to avoid excess lower-back arch."),
    ("Upright Row", "compound", "shoulders", "traps", "barbell", "intermediate",
     "Pull the bar straight up along your body to chest height, leading with the elbows."),

    # ── TRICEPS ─────────────────────────────────────────────────────
    ("Bench Dip", "bodyweight", "triceps", "shoulders", "bench", "beginner",
     "With hands on a bench behind you and feet out front, lower your hips toward the floor and press back up."),
    ("Cable Overhead Extension", "isolation", "triceps", None, "cable", "beginner",
     "Facing away from a low cable, extend the rope overhead by straightening the elbows."),
    ("Cable Pushdown", "isolation", "triceps", None, "cable", "beginner",
     "Using a bar attachment, push the cable down until your arms are fully extended, then return under control."),
    ("Close-Grip Bench Press", "compound", "triceps", "chest", "barbell", "intermediate",
     "Using a shoulder-width or narrower grip, lower the bar to the chest and press up, emphasizing the triceps."),
    ("Diamond Push-up", "bodyweight", "triceps", "chest", "bodyweight", "intermediate",
     "With hands close together forming a diamond shape, perform a push-up emphasizing the triceps."),
    ("Dip (Triceps Focus)", "bodyweight", "triceps", "chest", "dip bar", "intermediate",
     "Keeping your torso upright, lower and press between parallel bars to bias the triceps over the chest."),
    ("Dumbbell Overhead Extension", "isolation", "triceps", None, "dumbbell", "beginner",
     "Holding a dumbbell overhead with both hands, lower it behind your head by bending the elbows, then extend up."),
    ("Dumbbell Skull Crusher", "isolation", "triceps", None, "dumbbell", "intermediate",
     "Lying on a bench, lower dumbbells toward your temples by bending at the elbows, then press back up."),
    ("Incline Skull Crusher", "isolation", "triceps", None, "barbell", "intermediate",
     "On an incline bench, lower the bar toward your forehead by bending at the elbows, then extend back up."),
    ("JM Press", "compound", "triceps", "chest", "barbell", "advanced",
     "A hybrid between a close-grip bench press and skull crusher, lowering the bar toward the upper chest/neck."),
    ("Kickback", "isolation", "triceps", None, "dumbbell", "beginner",
     "Bent forward with your upper arm parallel to the floor, extend the forearm back and squeeze the triceps."),
    ("Machine Tricep Extension", "isolation", "triceps", None, "machine", "beginner",
     "Seated at the machine, extend your arms against the resistance pad, then return under control."),
    ("Overhead Cable Tricep Extension", "isolation", "triceps", None, "cable", "beginner",
     "Facing away from a low cable, extend the rope overhead by straightening the elbows."),
    ("Overhead Triceps Extension", "isolation", "triceps", None, "dumbbell", "beginner",
     "Holding a dumbbell overhead with both hands, lower it behind your head by bending the elbows, then extend up."),
    ("Reverse-Grip Pushdown", "isolation", "triceps", None, "cable", "intermediate",
     "Using an underhand grip on a straight bar, push the cable down to emphasize the inner triceps head."),
    ("Rope Pushdown", "isolation", "triceps", None, "cable", "beginner",
     "Using a rope attachment, push down and spread the rope ends apart at the bottom for a full contraction."),
    ("Single-Arm Cable Pushdown", "isolation", "triceps", None, "cable", "beginner",
     "Using a single handle, push the cable down one arm at a time to address side-to-side imbalances."),
    ("Single-Arm Overhead Extension", "isolation", "triceps", None, "dumbbell", "beginner",
     "Holding one dumbbell overhead, lower it behind your head using one arm, then extend back up."),
    ("Skull Crusher", "isolation", "triceps", None, "barbell", "intermediate",
     "Lying on a bench, lower the bar toward your forehead by bending only at the elbows, then extend back up."),
    ("Straight-Bar Pushdown", "isolation", "triceps", None, "cable", "beginner",
     "Using a straight bar attachment, push the cable down until your arms are fully extended."),
    ("Tricep Pushdown", "isolation", "triceps", None, "cable", "beginner",
     "Using a bar or rope attachment, push the cable down until your arms are fully extended, then return under control."),
    ("V-Bar Pushdown", "isolation", "triceps", None, "cable", "beginner",
     "Using a V-bar attachment, push the cable down to full extension, keeping elbows pinned to your sides."),
]


def _dedup(exercises):
    seen = set()
    result = []
    for entry in exercises:
        name = entry[0]
        if name in seen:
            continue
        seen.add(name)
        result.append(entry)
    return result


PREDEFINED_EXERCISES = _dedup(PREDEFINED_EXERCISES)


def seed_exercises(db: Session) -> None:
    """
    Inserts any predefined exercise that doesn't exist yet, AND updates the
    metadata of ones that already exist if the predefined list has changed.
    Only touches rows where created_by is NULL (global catalog), never a
    user's custom exercises.
    """
    existing = {
        e.name: e
        for e in db.query(models.Exercise).filter(models.Exercise.created_by.is_(None)).all()
    }
    for name, category, muscle_group, secondary_muscle, equipment, difficulty, instructions in PREDEFINED_EXERCISES:
        if name in existing:
            exercise = existing[name]
            changed = False
            for field, value in [
                ("category", category),
                ("muscle_group", muscle_group),
                ("secondary_muscle", secondary_muscle),
                ("equipment", equipment),
                ("difficulty", difficulty),
                ("instructions", instructions),
            ]:
                if getattr(exercise, field) != value:
                    setattr(exercise, field, value)
                    changed = True
        else:
            db.add(models.Exercise(
                name=name,
                category=category,
                muscle_group=muscle_group,
                secondary_muscle=secondary_muscle,
                equipment=equipment,
                difficulty=difficulty,
                instructions=instructions,
                is_custom=False,
                created_by=None,
            ))
    db.commit()